Feature mortar overhaul
DarklightGames/DarkestHour pull request #1132
Opened 2020-09-14 11:56 UTC by mimiski

Highlights of this pull request:
 - reviewed & slightly refactored map markers: 
   - added 3 new methods `DHMapMarker.CanSeeMarker`, `DHMapMarker.CanPlaceMarker` & `DHMapMarker.CanRemoveMarker` that handle visibility/addition/removal of map markers per each player (eg their class),
   - refactored marker overwriting rules (`PERSONAL`, `SQUAD`, `TEAM`) & marker scope (`UNIQUE_PER_GROUP`, `UNIQUE`, `OFF`) so they have clearer semantics and enable marking targets per squad for artillery operators
 - each SL can now mark HE & smoke requests for artillery operators; targets are labeled with squads name
 - added  LeIG18 to the construction menu
 - artillery operators include: mortars, M7 Priest crewmen, LeIG18 operators
 - added range tables for mortars, Priest & LeIG18

To do:
- [ ] replace temporary target markers with colorful ovals
- [ ] adjust font size in range table

2020-09-15 13:53 UTC, shiftycats requested changes
Here's the list of issues i found so far after a brief test.

**Bugs:**
- [x] MP: Fire support markers cause log spam if player hasn't spawned yet **(fixed in a93b6ba)**:
```
DHMapMarker_FireSupport_HE None (Function DH_Engine.DHMapMarker_FireSupport.CanSeeMarker:002E) Accessed None 'PC'
```
- [x] ~~MP/SP: Shell explosions are not displayed on the map.~~

**Features:**
- [x] Remove decimals from firing tables **(fixed in e3dd9107182eced36892c209047fd4c9e048c7c0)**.
- [x] Firing tables use incorrect units. Elevation dial is in degrees—not mils **(fixed in e3dd9107182eced36892c209047fd4c9e048c7c0)**. 
**EDIT: This applies only to mortars and whatever else uses degrees to measure elevation.**
- [ ] Invert horizontal dials (right should be positive) **(fixed in 708618344bc8fa835808b797eda7d6b12e553520)**
**EDIT: On mortars**
- [ ] Half-stops (0.5 degree) are not denoted in any way on the elevation dial, they are just clicked through without moving the dial. Player has no way of knowing which value he's sitting on.
- [ ] Mortar operator should not have access to fire support markers (unless in single-player).
- [x] Fire support markers should not be placeable via the map menu (unless in single-player). Squad leaders are supposed to have a direct view of the thing they are marking **(fixed in fa22d895f46fd29c69acc50b216db5a5b45d82c5, disabled for single player as well)**
- [x] Squad should only have 1 fire support marker active at a time (either smoke or HE). Currently they can place both of them, which adds clutter. **(fixed in 0727de7a45594b83c33a313e7237dfc8e8f003cd)**
- [x] Fire support markers expire too fast. Perhaps they should never expire if marker's owner is close enough
**(decided on [Discord](https://discordapp.com/channels/339838693617565697/712779622751797288/755488014129692824) to leave infinite expiry time, for now SLs should handle marker removal themselves; disabled expiry of artillery requests in  c79757176de16ae3e1451e781a5cc0a4549f3b51)**
- [x] Squad leader should receive a notification when his marker has expired.
**(decided on [Discord](https://discordapp.com/channels/339838693617565697/712779622751797288/755488014129692824) to leave infinite expiry time, for now SLs should handle marker removal themselves; disabled expiry of artillery requests in  c79757176de16ae3e1451e781a5cc0a4549f3b51)**
- [ ] Distance to a target and a deflection angle need to be displayed somewhere!
This one is important, as there's no point in having firing tables and fancy dials if there's no data to dial in. The values can be displayed on the HUD after selecting an active target. This can be done either via the map or automatically (the one we are aiming at is selected).
- [ ] Fire support markers need to be displayed on the horizontal dial.

2020-09-15 14:44 UTC, mimiski commented
Ad. `MP/SP: Shell explosions are not displayed on the map.`
I'm not sure what that means - could you elaborate more on that? You mean there are no hit markers at all? Are you sure you are hitting within the radius of the artillery request? What are the steps to reproduce?

2020-09-15 14:44 UTC, mimiski commented
> Ad. `MP/SP: Shell explosions are not displayed on the map.`
> I'm not sure what that means - could you elaborate more on that? You mean there are no hit markers at all? Are you sure you are hitting within the radius of the artillery request? What are the steps to reproduce?

2020-09-15 14:49 UTC, shiftycats commented
> I'm not sure what that means - could you elaborate more on that? You mean there are no hit markers at all? Are you sure you are hitting within the radius of the artillery request? What are the steps to reproduce?

Correct. Hit markers don't work.

Steps to reproduce in multiplayer:
1. Launch 2 clients.
2. Set marker on first client.
3. Use mortar on the second client and try to hit the target as closely as possible.

Does not work in single-player either.

2020-09-15 14:50 UTC, mimiski commented
Ad. ` Firing tables use incorrect units. Elevation dial is in degrees—not mils.`
I would consequently use degrees instead of mils then.

Ad. ` Invert horizontal dials (right should be positive).`
That is the way it is right now.

Ad. `Half-stops (0.5 degree) are not denoted in any way on the elevation dial, they are just clicked through without moving the dial. Player has no way of knowing which value he's sitting on.`
It's a matter of the scale on the dial. If its granularity is smaller (eg. 0.5) then:
 - a) the dial moves unnaturally fast every time even a slightest adjustment is made
 -  b) smaller granularity causes stutter of the readout on extreme values of yaw. You can reproduce it by by setting `PitchScaleStep=1.0` to and `YawScaleStep=1.0` for M7Priest and then trying out extreme values of both pitch and readout
so the conclusion would be we have to leave the scale granularity like that or somehow fix b).

Ad. `Mortar operator should not have access to fire support markers (unless in single-player).`
Could you elaborate more on that? You mean they shouldn't be able to mark targets? That's how it is right now. What are the steps to reproduce that?

2020-09-15 14:58 UTC, shiftycats commented
> Could you elaborate more on that? You mean they shouldn't be able to mark targets? That's how it is right now. What are the steps to reproduce that?

Mortar operators can put down markers by right-clicking on the map or by using the command menu when they are squad leaders.

> I would consequently use degrees instead of mils then.

Forgot to mention: this only applies to mortars and whatever else uses degrees on their dials. M7 uses mils if i'm not mistaken.

2020-09-15 14:58 UTC, mimiski commented
Ad. `Distance to a target and a deflection angle need to be displayed somewhere!
This one is important, as there's no point in having firing tables and fancy dials if there's no data to dial in. The values can be displayed on the HUD after selecting an active target. This can be done either via the map or automatically (the one we are aiming at is selected).`
Do you mean there should be a numeric readout with the exact values of pitch and yaw?

2020-09-15 15:03 UTC, shiftycats commented
> Do you mean there should be a numeric readout with the exact values of pitch and yaw?

A player needs to know the distance to the fire support marker and much he's off horizontally wise from the thing (the deflection angle). This functionality is sort of provided by the ruler marker, but players should only use the ruler when there's no fire support marker available.

2020-09-15 15:20 UTC, mimiski commented
By the way - I revisited the spotting scope layout and that's the effect (very strongly inspired by HLL)
![spotting-scope](https://user-images.githubusercontent.com/56321463/93230244-c36b9d00-f777-11ea-9032-693136a7cd38.png)

2020-09-15 15:23 UTC, shiftycats commented
Love it!

2020-09-15 15:23 UTC, shiftycats commented
**Bug:** 
Can't exit the "looking into binoculars" position in M7 Priest.

**Replications steps:**
1. Get in the gunner seat.
2. Scroll all the way up to the binoculars position.
2. Try to scroll back down and fail.

2020-09-15 15:34 UTC, shiftycats commented
> Ad. Invert horizontal dials (right should be positive).
That is the way it is right now.

Not on mortars. M7 dial rotates in the proper direction though.

2020-09-15 16:05 UTC, shiftycats commented on DH_Engine/Classes/DHArtillerySpottingScope.uc
> +    var int Degrees;                                    // Pitch, in degrees.
Just use `Pitch` or `Elevation` as a name or something. It's confusing since the values can be in degrees or mils.

2020-09-15 16:59 UTC, mimiski commented
Ad. `Fire support markers expire too fast. Perhaps they should never expire if marker's owner is close enough.`
You mean that as long as the marker's owner is eg. within 100m the marker should not expiry? What if the owner leaves the circle around 100m from the marker? Should the marker be alive for another, let's say, 10 minutes?

2020-09-15 17:05 UTC, mimiski commented
Ad. ` Fire support markers need to be displayed on the horizontal dial.`
Do you mean on the pitch yaw readout or on the compass?

2020-09-15 17:18 UTC, mimiski reviewed
> **Bug:**
> Can't exit the "looking into binoculars" position in M7 Priest.
> 
> **Replications steps:**
> 
> 1. Get in the gunner seat.
> 2. Scroll all the way up to the binoculars position.
> 3. Try to scroll back down and fail.

I cannot reproduce that. You mean you get to this view (binoculars) and you get stuck in it (you cannot get back to the gun)?
![image](https://user-images.githubusercontent.com/56321463/93243236-3715a600-f788-11ea-9c79-a4ea18547579.png)

2020-09-15 17:20 UTC, shiftycats commented
> Ad. `Fire support markers expire too fast. Perhaps they should never expire if marker's owner is close enough.`
> You mean that as long as the marker's owner is eg. within 100m the marker should not expiry? What if the owner leaves the circle around 100m from the marker? Should the marker be alive for another, let's say, 10 minutes?

Correct. Let it sit for another 10 minutes once the owner is out of range. Make the circle more generous though, like around 300m (squad leaders can spot things from quite far away).

2020-09-15 17:30 UTC, shiftycats commented
> Does this condition have to be checked on every tick?

No, there's no need to check it often. Every minute is more than sufficient.

2020-09-15 18:38 UTC, shiftycats commented
> Can't exit the "looking into binoculars" position in M7 Priest.

False alarm. My controls were messed up.

2020-09-16 06:56 UTC, cmbasnett commented
I would advise changing the `degs` to `°` to reduce visual noise and make the chart easier to parse.

2020-09-16 21:02 UTC, shiftycats commented
### Targetting widgets

![rect1003](https://user-images.githubusercontent.com/36604408/93391923-99e66a80-f878-11ea-8488-e7208e6039c9.png)

### Target blips on the yaw dial
![rect1119](https://user-images.githubusercontent.com/36604408/93391950-a5399600-f878-11ea-811d-7c0d46c93233.png)

2020-09-16 21:22 UTC, mimiski commented
> I would advise changing the `degs` to `°` to reduce visual noise and make the chart easier to parse.

Changed in 794423cb0c5b943d4719813a79c024622b4d6625

2020-09-20 08:52 UTC, shiftycats commented on DH_Engine/Classes/DHVehicleCannonPawn.uc
> +    WeaponRotation.Yaw = VehWep.Rotation.Yaw;
This breaks the deflection readout for mortars. `VehicleWeapon` rotation is not utilized on mortars; it's always set to some arbitrary value.

2020-09-20 16:31 UTC, mimiski commented
Regarding ` Mortar operator should not have access to fire support markers (unless in single-player).`:
How about disabling seeing artillery hits on players own markers instead of completely disabling artillery requests for SLs that play artillery roles?

2020-09-20 16:36 UTC, shiftycats commented
> 
> 
> Regarding ` Mortar operator should not have access to fire support markers (unless in single-player).`:
> How about disabling seeing artillery hits on players own markers instead of completely disabling artillery requests for SLs that play artillery roles?

That works.

2020-09-20 16:40 UTC, mimiski reviewed
> > Regarding ` Mortar operator should not have access to fire support markers (unless in single-player).`:
> > How about disabling seeing artillery hits on players own markers instead of completely disabling artillery requests for SLs that play artillery roles?
> 
> That works.

Implemented in 097c414307e3811a1a1e81f9f88d3ee98020dd3e

2020-09-20 16:41 UTC, mimiski commented
> > Regarding ` Mortar operator should not have access to fire support markers (unless in single-player).`:
> > How about disabling seeing artillery hits on players own markers instead of completely disabling artillery requests for SLs that play artillery roles?
> 
> That works.

2020-09-20 16:45 UTC, shiftycats commented on DH_Engine/Classes/DHVehicleCannonPawn.uc
> +    WeaponRotation.Yaw = VehWep.Rotation.Yaw;
The deflection readout was completely off on mortars when i tested this.

2020-09-20 22:29 UTC, shiftycats commented on DH_Engine/Classes/DHVehicleCannonPawn.uc
> +    Player = DHPlayer(PC);
Here's another redundant variable.

2020-09-21 21:33 UTC, shiftycats approved these changes

2020-09-21 21:39 UTC, shiftycats requested changes
See [project backlog](https://github.com/DarklightGames/DarkestHour/projects/8).

2021-08-17 20:37 UTC, closed without merging