Myshkova_River-Overhaul
DarklightGames/DarkestHour pull request #1427
Opened 2022-04-13 16:54 UTC by randomguy3174

-removed all APs;
-removed first two caps;
-removed vehicle pool from constructions;
-myshkova intersection and bridgehead now one big cap;
-all caps, but last(hill 410) got updated volume;
-caps no longer can be recaptured;
-added objective spawns(inf and veh), precap minefields;
-roles, vehicles, arty and activation logic been revised;
-reinforcement interval been fixed and triggers updated;
-added 18min timer per cap;
-moved setup phase black box.

2022-04-16 09:01 UTC, GDrukenmiller submitted a review, later dismissed

2022-04-16 09:13 UTC, GDrukenmiller commented
I like most of the changes, but this needs to be reverted to standard ticket based.

2022-04-16 09:15 UTC, GDrukenmiller requested changes
I like most of the changes, but this needs to be reverted to standard ticket based.

2022-05-23 09:30 UTC, cmbasnett requested changes
Something is wrong with this PR, it has way too many commits in it.

2022-05-23 10:51 UTC, closed without merging