US/SOV/GER roles overhaul.
DarklightGames/DarkestHour pull request #1445
Opened 2022-06-05 15:17 UTC by randomguy3174

-DHUSRadioOperatorRoles carbine/grease/springfield -> garand
-DHUSAntiTankRoles carbine/grease -> garand
-DHUSEngineerRoles carbine/springfield -> carbine/springfield/garand
-DHUSCorporalRoles thompson/thompson20/garand -> thompson/grease/garand

-DHSOVRiflemanRoles m38/m91 -> m91
-DHSOVEngineerRoles m38 -> m38/m91
-DHSOVCorporalRoles svt40 -> svt40/m91
-DHSOVSergeantRoles ppd40/svt40/svt38 -> svt38/m91
-DHSOVAssaultRoles ppsh41 -> ppsh41/ppd40
-DHSOVAntiTankRoles Nagant1895 -> Nagant1895/TT -satchel

-DHGERadioOperatorRoles k98 -> k98/k98no cover +stiel granate
-DHGEEngineerRoles k98 -> k98/k98no cover -GLWeapon
-DHGEAntiTankRoles -GLWeapon

2022-06-05 17:52 UTC, toastertoasts commented
Nice,

Would add carbine option to the guys carrying heavy stuff, and the sergeant this is not supported by TOE though so this is just my dumb opinion;
-DHUSAntiTankRoles carbine/grease -> garand/carbine
-DHUSRadioOperatorRoles carbine/grease/springfield -> garand/carbine
-Also maybe add carbine to sergeant role;

2022-06-05 21:07 UTC, GarlicAAZ requested changes
PPD should be kept in soviet sergeant class, otherwise some undesired balance changes may occur on earlywar maps

2022-06-07 00:06 UTC, GarlicAAZ approved these changes

2022-06-07 00:09 UTC, randomguy3174 commented
> Nice,
> 
> Would add carbine option to the guys carrying heavy stuff, and the sergeant this is not supported by TOE though so this is just my dumb opinion; -DHUSAntiTankRoles carbine/grease -> garand/carbine -DHUSRadioOperatorRoles carbine/grease/springfield -> garand/carbine -Also maybe add carbine to sergeant role;

idea is to have garand as baseline and let mappers/community/common sense decide destiny of additional weapons per map basis

2022-06-09 01:56 UTC, cmbasnett approved these changes

2022-06-09 01:57 UTC, merged