Added a broadcasted message when a vehicle pool is activated.
DarklightGames/DarkestHour pull request #1605
Opened 2023-05-30 15:32 UTC by LordDz

Vehicle pools are really important to the team, but they're not broadcast when constructed.
As a logi player I'd like this to be broadcast so I don't have to spend time on telling the team this.

2023-05-30 21:26 UTC, cmbasnett commented on DH_Engine/Classes/DHPlatoonVPMessage.uc
> +class DHPlatoonVPMessage extends ROGameMessage
I would just rename this to `DHVehiclePoolMessage`.

2023-05-30 21:26 UTC, cmbasnett commented on DH_Engine/Classes/DHPlatoonVPMessage.uc
> +    var localized string ConstructedMessage;
Indentation is incorrect here, just bring it to the left one.

2023-05-31 16:13 UTC, LordDz commented on DH_Engine/Classes/DHPlatoonVPMessage.uc
> +            return default.OverrunMessage;
@cmbasnett I've removed the unused messages and fixed the indent.

2023-06-02 18:21 UTC, cmbasnett requested changes

2023-06-02 18:21 UTC, cmbasnett commented on DH_Engine/Classes/DHVehiclePoolMessage.uc
> +            return default.ConstructedMessage;
This one is also unused it seems.

2023-06-02 21:27 UTC, LordDz commented on DH_Engine/Classes/DHVehiclePoolMessage.uc
> +            return default.ConstructedMessage;
Fixed!

2023-06-02 22:45 UTC, cmbasnett approved these changes

2023-06-02 22:55 UTC, merged