Set Shovel BuildFireMode to automatic
DarklightGames/DarkestHour pull request #1606
Opened 2023-05-30 21:21 UTC by LordDz

Simple change, but so nice for all logi players.
Nothing more than that, really.

2023-05-30 22:12 UTC, shiftycats requested changes

2023-05-30 22:36 UTC, LordDz commented on DH_Equipment/Classes/DHShovelBuildFireMode.uc
> +class DHShovelBuildFireMode extends DHAutomaticFire;
I tried doing that, but then it plays the digging animation + sound but it never seems to actually build anything, it just shovels on with no progress done to the construction.

2023-05-31 02:54 UTC, shiftycats commented on DH_Equipment/Classes/DHShovelBuildFireMode.uc
> +class DHShovelBuildFireMode extends DHAutomaticFire;
Right. When the release flag is false, `ModeDoFire` event is continuously called while the mouse button is pressed. And every time it's run, it clears the construction actor. That's why there's no construction progress.

https://github.com/DarklightGames/DarkestHour/blob/2533f7e657a91fb375380531b32c55018abfa6f9/DH_Equipment/Classes/DHShovelBuildFireMode.uc#L62-L64

To fix this, add a `event ModeDoFire();` line in the `Building` state to override the function so it's not doing anything while digging is in progress.

2023-05-31 03:06 UTC, shiftycats commented on DH_Equipment/Classes/DHShovelBuildFireMode.uc
> +class DHShovelBuildFireMode extends DHAutomaticFire;
Also, it's a good idea to add a `StopFire` call to stop `ModeDoFire` from being called needlessly when construction is done or the player is no longer looking at it.

```diff
 event ModeDoFire()
 {
     Construction = none;
 
     if (AllowFire())
     {
         GotoState('Building');
     }
+    else
+    {
+        Weapon.StopFire(ThisModeNum);
+    }
 }
```

2023-05-31 15:51 UTC, LordDz commented on DH_Equipment/Classes/DHShovelBuildFireMode.uc
> +class DHShovelBuildFireMode extends DHAutomaticFire;
Updated it with your suggestions @shiftycats.

2023-05-31 22:01 UTC, shiftycats approved these changes
Looks good.

2023-05-31 22:02 UTC, merged