Additon of "marksman" role for axis
DarklightGames/DarkestHour pull request #1613
Opened 2023-06-12 15:03 UTC by Enfield-303

Historically, there was no distinction between snipers with the ZF39 (4x power) scope and those with the ZF41 (1.5x power) scope, however the ZF41 was used in a role much similar to designated marksmen today, and the ZF41 was far more numerous than the ZF39

https://www.youtube.com/watch?v=sBstpqUAniw (citation)

Proposed changes would be the reduction of higher tier snipers (those with zf39 and zf4 scopes), addition of a new "marksman" role, and a replacement for those that were reduced, I.E changing a map from 2 snipers to 1, but then adding a marksman.

The marksman role is named as such in code and with standard naming conventions, but within the native names for the faction, it is still named "scharfschütze" as there was no NAMED distinction within the Wehrmacht and SS, only one with how the scope was USED.

As well as this, the name marksman is there so that players can understand that this isnt a proper sniper role, it is one similar to that of a designated marksman.

2023-06-12 18:07 UTC, colinbasnettskyboxlabs commented on DH_Engine/Classes/DHAxisMarksmanRoles.uc
> +    AltName="Scharfsch�tze" //the native role name reflects this, but the translated name is there so that people can understand that this isnt a true "sniper"
Use Windows -1252 encoding when saving this file, otherwise the text gets corrupted

2023-06-13 21:36 UTC, cmbasnett requested changes
One last encoding issue

2023-06-13 21:36 UTC, cmbasnett commented on DH_Engine/Classes/DHAxisSniperRoles.uc
> +    AltName="Scharfschütze"
:(

2023-06-13 21:41 UTC, Enfield-303 commented on DH_Engine/Classes/DHAxisSniperRoles.uc
> +    AltName="Scharfschütze"
:)

2023-06-13 21:45 UTC, cmbasnett approved these changes

2023-06-13 23:55 UTC, merged