Feature/resupply grenades
DarklightGames/DarkestHour pull request #1623
Opened 2023-07-16 11:31 UTC by LordDz

Resupply points now refill grenade ammo and give back grenades that have been fully used.

2023-07-20 20:49 UTC, cmbasnett requested changes

2023-07-20 20:49 UTC, cmbasnett commented on DH_Engine/Classes/DHPawn.uc
> +    if (RI != None)
Invert this to reduce nesting (i.e., `if (RI == none) return`.

2023-07-20 20:49 UTC, cmbasnett commented on DH_Engine/Classes/DHPawn.uc
> +        }
This should just be a loop.

2023-09-17 09:46 UTC, closed without merging

2023-09-17 09:46 UTC, LordDz commented
https://github.com/DarklightGames/DarkestHour/pull/1640